[package]
name = "import_phrases"
version = "0.1.0"
edition = "2021"
license = "MIT"

[[bin]]
name = "import_phrases"
path = "main.rs"

[dependencies]
libchinese-core = { path = "../../core" }
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
