[workspace]
members = [
    "core",
    "libpinyin",
    "libzhuyin",
    "tools",
    "tools/inspect_redb",
    "tools/list_fst_keys"
    ,"tools/serialize_ngram"
    ,"tools/estimate_interpolation"
    ,"tools/gen_bigrams_from_tables"
]
resolver = "2"
