[workspace]
members = [
    "core",
    "libpinyin",
    "libzhuyin",
    "tools/convert_table",
    "tools/inspect_converted",
    "tools/show_lexicon_entry",
    "tools/gen_word_bigrams"
]
resolver = "2"
