[workspace]
members = [
    "core",
    "libpinyin",
    "libzhuyin",
    "tools/convert_table",
    "tools/inspect_converted",
    "tools/export_userdict",
    "tools/import_phrases",
]
resolver = "2"
