[package]
name = "libpinyin"
version = "0.1.0"
edition = "2021"
description = "Rust reimplementation of libpinyin"
license = "MIT"

[dependencies]
libchinese-core = { path = "../core" }
phf = { version = "0.11", features = ["macros"] }
regex = "1.11"
clap = { version = "4.5", features = ["derive"] }
