[package]
name = "gen_bigrams_from_tables"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
fst = "0.4"
redb = "2.1"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
