[package]
name = "estimate_interpolation"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
fst = "0.4"
redb = "2.1"
clap = { version = "4.5", features = ["derive"] }
bincode = "1.3"
libchinese-core = { path = "../../core" }
serde = { version = "1.0", features = ["derive"] }
