[package]
name = "serialize_ngram"
version = "0.1.0"
edition = "2021"

[dependencies]
libchinese-core = { path = "../../core" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
anyhow = "1.0"

