[package]
name = "inspect_converted"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "inspect_converted"
path = "src/main.rs"

[dependencies]
fst = "0.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
libchinese-core = { path = "../../core" }
